# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b7c30bed7d1d3f28e263b98132d75fe863672d482d96cce6cdfd983f3c28a1174170abad185df9c577f033e4bc6176432bd2fb5733f684f024f027746ed12c00

test:
  secret_key_base: 0b5b67730c4d00d601b5e52639f0ed6157e2602565ffa1360203f903641a04ff3f666c8428302beeb54746faeb9d2c72e4c3187a895d3f549790f89bf0a681df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
